# Initial AI platform schema for Baraq. Generated manually because the review
# environment does not ship Django dependencies.
from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0002_alter_studentsourceinteraction_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('provider', models.CharField(choices=[('auto', 'Automatic router'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('local', 'Local model'), ('mock', 'Mock provider')], max_length=20)),
                ('model_name', models.CharField(max_length=160)),
                ('supported_tasks', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('input_cost_per_million', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('output_cost_per_million', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={'ordering': ('priority', 'name')},
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('character', models.CharField(choices=[('fahes', 'Fahes'), ('khota', 'Khota'), ('rasheed', 'Rasheed'), ('kholasa', 'Kholasa'), ('sada', 'Sada')], max_length=20)),
                ('task_type', models.CharField(choices=[('fahes_generate_quiz', 'Fahes: Generate quiz'), ('khota_generate_plan', 'Khota: Generate study plan'), ('rasheed_recommend', 'Rasheed: Recommendations'), ('kholasa_summarize', 'Kholasa: Summarize'), ('sada_transcribe', 'Sada: Transcribe audio')], max_length=50)),
                ('system_prompt', models.TextField()),
                ('prompt_template', models.TextField()),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ('name', '-version')},
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('character', models.CharField(choices=[('fahes', 'Fahes'), ('khota', 'Khota'), ('rasheed', 'Rasheed'), ('kholasa', 'Kholasa'), ('sada', 'Sada')], max_length=20)),
                ('task_type', models.CharField(choices=[('fahes_generate_quiz', 'Fahes: Generate quiz'), ('khota_generate_plan', 'Khota: Generate study plan'), ('rasheed_recommend', 'Rasheed: Recommendations'), ('kholasa_summarize', 'Kholasa: Summarize'), ('sada_transcribe', 'Sada: Transcribe audio')], max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('validating', 'Validating'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('requested_provider', models.CharField(choices=[('auto', 'Automatic router'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('local', 'Local model'), ('mock', 'Mock provider')], default='auto', max_length=20)),
                ('selected_provider', models.CharField(blank=True, max_length=20)),
                ('selected_model', models.CharField(blank=True, max_length=160)),
                ('input_payload', models.JSONField(default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('schema_version', models.CharField(default='1.0', max_length=30)),
                ('provider_request_id', models.CharField(blank=True, max_length=255)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('consent_to_dataset', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='sources.studentsourcecollection')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='ai_platform.promptversion')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='sources.studentsource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='AIOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_json', models.JSONField(default=dict)),
                ('raw_provider_response', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('needs_review', 'Needs review')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('groundedness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('source_references', models.JSONField(blank=True, default=list)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('is_used_by_student', models.BooleanField(default=False)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='ai_platform.airequest')),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_helpful', models.BooleanField()),
                ('feedback_type', models.CharField(choices=[('general', 'General'), ('incorrect', 'Incorrect'), ('not_grounded', 'Not grounded in source'), ('unclear', 'Unclear'), ('too_easy', 'Too easy'), ('too_hard', 'Too hard'), ('too_long', 'Too long'), ('too_short', 'Too short'), ('other', 'Other')], default='general', max_length=30)),
                ('issue_types', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True)),
                ('corrected_output', models.JSONField(blank=True, default=dict)),
                ('allow_training', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_platform.aioutput')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='SourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=160)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chunks', to='sources.studentsource')),
            ],
            options={'ordering': ('source_id', 'chunk_index')},
        ),
        migrations.CreateModel(
            name='TrainingDatasetCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anonymized_input', models.JSONField(default=dict)),
                ('expected_output', models.JSONField(default=dict)),
                ('pii_status', models.CharField(default='pending', max_length=30)),
                ('anonymization_status', models.CharField(default='pending', max_length=30)),
                ('human_review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_for_training', models.BooleanField(default=False)),
                ('dataset_version', models.CharField(blank=True, max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_candidates', to='ai_platform.aifeedback')),
                ('output', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_candidate', to='ai_platform.aioutput')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_training_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('dataset_version', models.CharField(max_length=50)),
                ('provider', models.CharField(choices=[('auto', 'Automatic router'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('local', 'Local model'), ('mock', 'Mock provider')], max_length=20)),
                ('model_name', models.CharField(max_length=160)),
                ('code_commit', models.CharField(blank=True, max_length=64)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_runs', to='ai_platform.promptversion')),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddConstraint(model_name='promptversion', constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_ai_prompt_name_version')),
        migrations.AddConstraint(model_name='promptversion', constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('task_type',), name='one_active_prompt_per_ai_task')),
        migrations.AddConstraint(model_name='aifeedback', constraint=models.UniqueConstraint(fields=('user', 'output'), name='one_ai_feedback_per_user_output')),
        migrations.AddConstraint(model_name='sourcechunk', constraint=models.UniqueConstraint(fields=('source', 'chunk_index'), name='unique_source_ai_chunk_index')),
        migrations.AddIndex(model_name='airequest', index=models.Index(fields=['user', 'status', '-created_at'], name='ai_req_user_status_idx')),
        migrations.AddIndex(model_name='airequest', index=models.Index(fields=['task_type', 'status'], name='ai_req_task_status_idx')),
        migrations.AddIndex(model_name='airequest', index=models.Index(fields=['input_hash', 'task_type'], name='ai_req_hash_task_idx')),
        migrations.AddIndex(model_name='sourcechunk', index=models.Index(fields=['source', 'content_hash'], name='ai_chunk_source_hash_idx')),
    ]
